apiVersion: v1
data:
  allowed_hosts_list: '[*]'
  debug_mode: true
kind: ConfigMap
metadata:
  name: django-config
---
apiVersion: v1
data:
  secret-key: ZDkzJDQmXngmNDQzYmY2eXUlIV9ndXJec2slNDhhYyEmXiEjI3ZoIWRxaSp1KGQoZXA=
kind: Secret
metadata:
  name: django-secret
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  ports:
  - name: http
    port: 8000
  selector:
    app: django-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
      - env:
        - name: ALLOWED_HOSTS_LIST
          valueFrom:
            configMapKeyRef:
              key: allowed_hosts_list
              name: django-config
        - name: DEBUG_MODE
          valueFrom:
            configMapKeyRef:
              key: debug_mode
              name: django-config
        - name: SECRET_KEY_VALUE
          valueFrom:
            secretKeyRef:
              key: secret-key
              name: django-secret
        image: pdziedziel/images:django1.4
        name: django
        ports:
        - containerPort: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: django-ingress
spec:
  rules:
  - host: django-app.com
    http:
      paths:
      - backend:
          service:
            name: django-service
            port:
              number: 8000
        path: /
        pathType: Prefix