apiVersion: v1
data:
  allowed_hosts_list: '[*]'
  debug_mode: "True"
kind: ConfigMap
metadata:
  labels:
    app: dev-django
  name: dev-configmap
  namespace: django-dev
---
apiVersion: v1
data:
  secret-key: ZDkzJDQmXngmNDQzYmY2eXUlIV9ndXJec2slNDhhYyEmXiEjI3ZoIWRxaSp1KGQoZXA=
kind: Secret
metadata:
  labels:
    app: dev-django
  name: dev-secret
  namespace: django-dev
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: dev-django
  name: dev-service
  namespace: django-dev
spec:
  ports:
  - name: http
    port: 8000
  selector:
    app: dev-django
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dev-django
  name: dev-deployment
  namespace: django-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-django
  template:
    metadata:
      labels:
        app: dev-django
    spec:
      containers:
      - env:
        - name: ALLOWED_HOSTS_LIST
          valueFrom:
            configMapKeyRef:
              key: allowed_hosts_list
              name: dev-configmap
        - name: DEBUG_MODE
          valueFrom:
            configMapKeyRef:
              key: debug_mode
              name: dev-configmap
        - name: SECRET_KEY_VALUE
          valueFrom:
            secretKeyRef:
              key: secret-key
              name: dev-secret
        image: pdziedziel/images:django1.4
        name: django
        ports:
        - containerPort: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: dev-django
  name: dev-ingress
  namespace: django-dev
spec:
  rules:
  - host: django-dev.com
    http:
      paths:
      - backend:
          service:
            name: dev-service
            port:
              number: 8000
        path: /
        pathType: Prefix