apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
spec:
  selector:
    matchLabels:
      app: django-app
  replicas: 1
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
      - name: django
        image: pdziedziel/images:django1.4
        ports:
        - containerPort: 8000
        env:
        - name: ALLOWED_HOSTS_LIST
          valueFrom:
            configMapKeyRef:
              name: django-config
              key: allowed_hosts_list
        - name: DEBUG_MODE
          valueFrom:
            configMapKeyRef:
              name: django-config
              key: debug_mode
        - name: SECRET_KEY_VALUE
          valueFrom:
            secretKeyRef:
              name: django-secret
              key: secret-key