apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: dev-
namespace: django-dev
commonLabels:
  app: dev-django

generatorOptions:
  disableNameSuffixHash: true

resources:
  - ../base
patchesStrategicMerge:
#  - deployment.yaml
  - ingress.yaml
