apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: test-
namespace: django-namespace
commonLabels:
  app: test-django

generatorOptions:
  disableNameSuffixHash: true

resources:
  - secret.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
